### ISSUE TITLE
运行错误是什么问题？

### ISSUE THREAD

**Issue by cnruan** [knightli2003/chia_plot#1]
['run.py', 'plot_config_example.json']
i= 0
i= 1
i= 2
i= 0
i= 1
i= 2
i= 0
i= 1
i= 2
i= 0
i= 1
i= 2
{'chia_path': '/usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/', 'farmer_public_key': '86cc2c1dcbfa4264115f51bd9f755d7f8b0221fc3769e6ebb5a5f0c55c5fddf35aadc2d8ccdea9504fc5f5b4b429ea9b', 'pool_public_key': 'a6bae557fc340d438ef142d9411e24f1d97d0898268e9c68f76bbb9fd16592f7094952bdf9efd1aa64fef2a9e5232e47', 'global_start_interval': 900, 'global_phase1_cnt': 22, 'pools': [{'pool_name': '101HDD1', 'pool_run_cnt': 3, 'pool_start_interval': 3600, 'threads': 8, 'thread_k': 32, 'thread_mem': 4000, 'thread_tmp_path': '/mnt/ssd1/101HDD1', 'thread_tmp_path2': '/mnt/ssd1/101HDD1', 'thread_target': '/mnt/192.168.1.101/hdd1', 'pool_cur_run_cnt': 0, 'pool_last_run_time': 0, 'pool_run_data': [{'thread_no': 1, 'run_status': 0}, {'thread_no': 2, 'run_status': 0}, {'thread_no': 3, 'run_status': 0}]}, {'pool_name': 'HP_800G_2', 'pool_run_cnt': 3, 'pool_start_interval': 3600, 'threads': 8, 'thread_k': 32, 'thread_mem': 3390, 'thread_tmp_path': '/media/plot/HP_800G_2', 'thread_tmp_path2': '/media/plot/HP_800G_2', 'thread_target': '/media/plot/ST_4T_01/farm2', 'pool_cur_run_cnt': 0, 'pool_last_run_time': 0, 'pool_run_data': [{'thread_no': 1, 'run_status': 0}, {'thread_no': 2, 'run_status': 0}, {'thread_no': 3, 'run_status': 0}]}, {'pool_name': 'HP_800G_3', 'pool_run_cnt': 3, 'pool_start_interval': 3600, 'threads': 8, 'thread_k': 32, 'thread_mem': 3390, 'thread_tmp_path': '/media/plot/HP_800G_3', 'thread_tmp_path2': '/media/plot/HP_800G_3', 'thread_target': '/media/plot/ST_4T_01/farm2', 'pool_cur_run_cnt': 0, 'pool_last_run_time': 0, 'pool_run_data': [{'thread_no': 1, 'run_status': 0}, {'thread_no': 2, 'run_status': 0}, {'thread_no': 3, 'run_status': 0}]}, {'pool_name': 'HP_900G_1', 'pool_run_cnt': 3, 'pool_start_interval': 3600, 'threads': 8, 'thread_k': 32, 'thread_mem': 3390, 'thread_tmp_path': '/media/plot/HP_900G_1', 'thread_tmp_path2': '/media/plot/HP_900G_1', 'thread_target': '/media/plot/ST_4T_01/farm2', 'pool_cur_run_cnt': 0, 'pool_last_run_time': 0, 'pool_run_data': [{'thread_no': 1, 'run_status': 0}, {'thread_no': 2, 'run_status': 0}, {'thread_no': 3, 'run_status': 0}]}]}
Traceback (most recent call last):
  File "run.py", line 297, in <module>
    pools_run()
  File "run.py", line 284, in pools_run
    init_pool()
  File "run.py", line 122, in init_pool
    plot_stat['start_time']
KeyError: 'start_time'
cleanup_pool_thread...

**Comment by knightli2003** [comment]
bugfix
